config/routes.rb
DeviseFacebook::Application.routes.draw do

  resources :feedbacks

  resources :sizes

  resources :paintings

  root :to => 'static_pages#home'

  root :to => 'static_pages#home'
  get "products/tags" => "products#tags", :as => :products_tags

  
  devise_for :users

  resources :products 
  
  resources :users

  resources :user_steps

  resources :products do
     member { post :vote }
     put :envio_df, on: :member
  end
  
  match '/tags', to: 'tags#show_tags'
  match '/auth/:provider/callback', to: 'authentications#create', as: 'signin'
  
  get 'tags/:tag', to: 'products#index', as: :tag
  
  get 'paypal/checkout', to: 'products#paypal_checkout'
  
  get '/comprar', to: 'products#comprar'
  
  get '/envio', to: 'products#envio'
  
  get '/tallas', to: 'products#tallas'
    
  get 'mercadopago/checkout', to: 'products#mercadopago_checkout'
  
  get "terms", to:'static_pages#terms'

  get "privacy", to:'static_pages#privacy'

  get "faq", to:'static_pages#faq'

  get "static_pages/start"

  get "static_pages/buy"

  get "static_pages/sell"

end

app/models/painting.rb
class Painting < ActiveRecord::Base
  attr_accessible :image, :name, :product_id
  mount_uploader :image, ImageUploader
  
  belongs_to :product
  
  validates_presence_of :image
  
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  # GET /paintings
  # GET /paintings.json
  def index
    @paintings = Painting.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @paintings }
    end
  end

  # GET /paintings/1
  # GET /paintings/1.json
  def show
    @painting = Painting.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @painting }
    end
  end

  # GET /paintings/new
  # GET /paintings/new.json
  def new
    @painting = Painting.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @painting }
    end
  end

  # GET /paintings/1/edit
  def edit
    @product = Product.find(params[:id])
    @painting = @product.paintings.create(params[:painting])
    
     respond_to do |format|
         format.html { redirect_to @painting, notice: 'Painting was successfully created.' }
         format.json { render json: @painting, status: :created, location: @painting }
         format.js
     end
  end

  # POST /paintings
  # POST /paintings.json
  def create
      @painting = Painting.create(params[:painting])
      @product = Product.last
      
     #@painting = @product.paintings.update_attributes(params[:painting])
    respond_to do |format|
        format.html { redirect_to @painting, notice: 'Painting was successfully created.' }
        format.json { render json: @painting, status: :created, location: @painting }
        format.js
    end
  end

  # PUT /paintings/1
  # PUT /paintings/1.json
  def update
    @painting = Painting.find(params[:id])

    respond_to do |format|
      if @painting.update_attributes(params[:painting])
        format.html { redirect_to @painting, notice: 'Painting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @painting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paintings/1
  # DELETE /paintings/1.json
  def destroy
    @painting = Painting.find(params[:id])
    @painting.destroy
    
    respond_to do |format|
      format.html { redirect_to paintings_url }
      format.json { head :ok }
      format.js 
    end
  end
end

def find_id
   @paintings = @product.paintings.first
   return @paintings.product_id
end

app/helpers/paintings_helper.rb
module PaintingsHelper
   
end

app/views/paintings/_form.html.erb
<%= form_for(@painting) do |f| %>
  <% if @painting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@painting.errors.count, "error") %> prohibited this painting from being saved:</h2>

      <ul>
      <% @painting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.number_field :product_id %>
  </div>
 
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paintings/_painting.html.erb
<% if @product.paintings.count == 1 %>
  	<%= image_tag(painting.image_url(:timeline)) %>
	<div class="actions_remove">
	   <!-- <%= link_to "edit", edit_painting_path(painting) %> |
	    <%= link_to "remove", painting, method: :delete, remote: true %> -->
  	</div>
</div>
<% else %>
  	<%= image_tag(painting.image_url(:thumb)) %>
	
	<div class="actions_remove">
	</div>
<% end %>

app/views/paintings/create.js.erb
<% if @painting.new_record? %>
	alert("Failed to upload painting: <%= j @painting.errors.full_messages.join(', ').html_safe %>");
	<% elsif @product.paintings.count == 1 %>
		$('#ajax-status').show();
	var i = 0;
  		$(".defaultMainImage").replaceWith('<%= escape_javascript(render(@painting)) %>');
		//$(".defaultMainImage").css('background', 'url(painting.image_url)');
		$(".painting").attr('id', 'painting_<%= @painting.id %>');
		$('#ajax-status').hide();
		<% else  %>
		<% if @product.paintings.count <= 4 %>
			$("li#image_small").hide();
			$("ul#productImagesSortable").append("<li id='smallImage' class='painting_<%= @painting.id %>'><%= escape_javascript(render(@painting)) %></li>");
			i += 1
			<% else %>
					alert("Just allow 4 pictures! Thanks");
		<% end %>
<% end %>

<% if @product.paintings.count >1 %>
	$('.<%= dom_id(@painting) %>').hover(
	     function () {
				$(this).append('<%= link_to image_tag("close.png"), @painting, method: :delete, remote: true, :id => "remove", :class => "remove_painting" %>');
			},
			function (){
				$(this).find("#remove").remove();
	  });
	


<% end %>

app/views/paintings/destroy.js.erb
$('.<%= dom_id(@painting) %>').fadeOut('slow');
$('.<%= dom_id(@painting) %>').remove();

app/views/paintings/edit.html.erb
<h1>Editing painting</h1>

<%= render 'form' %>

<%= link_to 'Show', @painting %> |
<%= link_to 'Back', paintings_path %>

app/views/paintings/index.html.erb
<h1>Listing paintings</h1>

<table>
  <tr>
    <th>Product</th>
    <th>Image</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @paintings.each do |painting| %>
  <tr>
    <td><%= painting.product_id %></td>
    <td><%= painting.image %></td>
    <td><%= painting.name %></td>
    <td><%= link_to 'Show', painting %></td>
    <td><%= link_to 'Edit', edit_painting_path(painting) %></td>
    <td><%= link_to 'Destroy', painting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Painting', new_painting_path %>

app/views/paintings/new.html.erb
<h1>New painting</h1>

<%= render 'form' %>

<%= link_to 'Back', paintings_path %>

app/views/paintings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product:</b>
  <%= @painting.product_id %>
</p>

<p>
  <b>Image:</b>
  <%= @painting.image %>
</p>

<p>
  <b>Name:</b>
  <%= @painting.name %>
</p>


<%= link_to 'Edit', edit_painting_path(@painting) %> |
<%= link_to 'Back', paintings_path %>