config/routes.rb
DeviseFacebook::Application.routes.draw do

  resources :feedbacks

  resources :sizes

  resources :paintings

  root :to => 'static_pages#home'

  root :to => 'static_pages#home'
  get "products/tags" => "products#tags", :as => :products_tags

  
  devise_for :users

  resources :products 
  
  resources :users

  resources :user_steps

  resources :products do
     member { post :vote }
     put :envio_df, on: :member
  end
  
  match '/tags', to: 'tags#show_tags'
  match '/auth/:provider/callback', to: 'authentications#create', as: 'signin'
  
  get 'tags/:tag', to: 'products#index', as: :tag
  
  get 'paypal/checkout', to: 'products#paypal_checkout'
  
  get '/comprar', to: 'products#comprar'
  
  get '/envio', to: 'products#envio'
  
  get '/tallas', to: 'products#tallas'
    
  get 'mercadopago/checkout', to: 'products#mercadopago_checkout'
  
  get "terms", to:'static_pages#terms'

  get "privacy", to:'static_pages#privacy'

  get "faq", to:'static_pages#faq'

  get "static_pages/start"

  get "static_pages/buy"

  get "static_pages/sell"

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  has_many :paintings
  has_many :sizes
  
  attr_reader :tag_list
  attr_reader :size_tokens
  attr_accessible :shipping, :total_price, :tipo_envio, :cp, :peso, :alto, :largo, :ancho, :envio_int, :envio_df, :color, :description, :material, :picture, :quantity, :refund_policy, :size, :title, :user_id, :brand, :price  
  attr_accessible :name, :image
  attr_accessible :tag_list
  attr_accessible :size_tokens
  attr_accessible :tag_tokens
  
  validates :price, :numericality => {:greater_than_or_equal_to => 0.01}, :on => :update
  validates_numericality_of :quantity, :greater_than => 0, :less_than => 5, :on => :update    
  validates :color, :description, :material, :refund_policy, :title, :brand, :presence => { :message => "*dato requerido" }, :allow_blank => true, :on => :update
  #validates :description, :material, :title, :refund_policy, :format => {:with => /^[a-zA-Z\d\s]*$/}
  acts_as_taggable
 
  has_reputation :votes, source: :user, aggregated_by: :sum
  
  

  def mercadopago_url(datos)
     client_id = '4268569064335968'
     client_secret = 'pa6nV2JXuGee00YUoXaHsI3fPGhUfNTc'
     mp_client = MercadoPago::Client.new(client_id, client_secret)
     payment = mp_client.create_preference(datos) 
   end
   
   def size_tokens=(tokens)
       self.size_ids = Size.ids_from_tokens(tokens)
   end
   
   def tag_tokens=(tokens)
         self.size_ids = Tag.ids_from_tokens(tokens)
     end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  
  def index
   if params[:tag]
       @products = Product.tagged_with(params[:tag])
   else
       @products = Product.order('created_at DESC').page(params[:page]))
       @tags = Tag.where("name like ?", "%#{params[:q]}%")
   end
   respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products.map(&:attributes) }
      format.js
    end
  end
  
  def avoid_nil(products)
     items = []
     products.each do |product|
        if product.title.nil? && product.description.nil?
        else
           items << product
        end
      end 
      return items
  end
  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    id = @product.user_id
    @user = User.find(id)
    @products = @user.products.all(:order => 'RANDOM()', :limit => 4)
    
    #@items = avoid_nil(@user.products.all)
    #@products = @items.find(:order => 'rating ASC', :limit => 2)
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
      format.js
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = current_user.products.create
    @paintings = Painting.all
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit

  def edit
    @product = current_user.products.find(params[:id])
    @paintings = @product.paintings.all
    @tags = @product.tags.all
    
      respond_to do |format|
          format.html 
          format.json 
          format.js 
      end
  end


  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.update_attributes(params[:product])
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = current_user.products.find(params[:id])
    #@product = Product.tagged_with(params[:tag_list])
     respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product }
        format.json { head :no_content }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end
  
  
  def paypal_checkout
         product = Product.find(params[:product_id])
         ppr = PayPal::Recurring.new(
          return_url: product_url(product),
          cancel_url: products_url,
          description: product.title,
          amount: product.total_price,
          currency: "MXN"
         )
         response = ppr.checkout
         if response.valid?
           redirect_to response.checkout_url
         else
           raise response.errors.inspect
        end
    end
    
  def envio_df 
   @product = Product.find(params[:id])
   @product.update_attributes(:shipping => params[:envio])
   @product.total_price = (@product.price + @product.shipping).to_i
   @product.save
 end
 
 def tallas
    @product = Product.find(params[:product_id])
 end
=begin
       logger.debug "parametro envio es: #{params[:envio]}\n\n\n\n\n\n"
       logger.debug "parametro envio es: #{@product.envio_df}\n\n\n\n\n\n"
       logger.debug "parametro envio es: #{@product.envio_int}\n\n\n\n\n\n"
       logger.debug "parametro envio es: #{params[:envio_df]}\n\n\n\n\n\n"
=end
  
  def comprar
     @product = Product.find(params[:product_id])
    
     user_cp = find_user_product(@product)
     current_user_cp = current_user.user_cp
    # logger.debug "#{user_cp}\n\n\n\n\n\n"
    # logger.debug "#{current_user_cp}\n\n\n\n\n\n"
     if @product.tipo_envio == "sobre"
        url = "http://rastreo2.estafeta.com:7001/Tarificador/admin/TarificadorAction.do?dispatch=doGetTarifas&cCodPosOri=#{user_cp}&cCodPosDes=#{current_user_cp}&cTipoEnvio=#{@product.tipo_envio}&cIdioma=Esp"
     else
        url = "http://rastreo2.estafeta.com:7001/Tarificador/admin/TarificadorAction.do?dispatch=doGetTarifas&cCodPosOri=#{user_cp}&cCodPosDes=#{current_user_cp}&cTipoEnvio=#{@product.tipo_envio}&cIdioma=Esp&nPeso=#{@product.peso}&nLargo=#{@product.largo}&nAncho=#{@product.ancho}&nAlto=#{@product.alto}"
     end
    # logger.debug "#{url}\n\n\n\n\n\n"
     require 'net/http'
     require 'rubygems'
     require 'nokogiri'
     require 'open-uri'
     
     doc = Nokogiri::HTML(open(url))
     @dias = []
     doc.css(':nth-child(6) .style5 strong , :nth-child(7) strong, :nth-child(8) strong').each do |node|
          @dias.push(node.text)
     end 
     logger.debug "#{@dias}\n\n\n\n\n\n"
      
     @tarifas = []
        doc.css(':nth-child(6) td:nth-child(8) , :nth-child(7) :nth-child(8), :nth-child(8) td:nth-child(8)').each do |node|
        @tarifas.push(node.text)
     end
    # logger.debug "#{@tarTer2}\n\n\n\n\n\n"
  end
  
  def envio
      @product = Product.find(params[:product_id])
   end
  
  def vote
      value = params[:type] == "up" ? 1 : -1
      @product = Product.find(params[:id])
      @product.add_or_update_evaluation(:votes, value, current_user)
      #redirect_to :back, notice: "Thank you for voting!"
      respond_to do |format|
        format.js
      end

  end
  def products_as_json(product)
     data = {
       "external_reference" => "ARTICLE-ID-#{product.id}",
       "items" => [
         {
           "id" => product.id,
           "title" => product.title,
           "description" => product.description,
           "quantity" => 1,
           "unit_price" => product.total_price.to_i,
           "currency_id" => "MEX",
           "picture_url" => "http://i1266.photobucket.com/albums/jj523/JulioAhuactzin/Safari3_zpsb24612a1.png"
         }
       ],
       "payer" => {
           "name"=> current_user.username,
           "surname"=> current_user.username,
           "email"=> current_user.email
         },
       "back_urls"=> {
         "pending"=> "https://www.site.com/pending",
         "success"=> "http://www.site.com/success",
         "failure"=> "http://www.site.com/failure"
       }
     }
     return data
    # logger.debug "#{json}\n\n\n\n\n\n"
  end

  # your_view.html.erb
  
  def mercadopago_checkout
      product = Product.find(params[:product_id])
      test = products_as_json(product)
     # logger.debug "#{test}\n\n\n\n\n\n"
      
      mp_data = product.mercadopago_url(test)
     # logger.debug "#{mp_data}\n\n\n\n\n\n"
      result = JSON.parse(mp_data.to_json)
     # logger.debug "#{result}\n\n\n\n\n\n"
      initpoint = result["init_point"]
     # logger.debug "#{initpoint}\n\n\n\n\n\n"
          redirect_to initpoint
    end
  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
  
=begin 
 def tags
     @tags = Product.tag_counts.where("tags.name LIKE ?", "%#{params[:q]}%")
     results = @tags.map(&:attributes)
     
          respond_to do |format|
            format.json { render :json => @tags.map(&:attributes) }
          end
  end
=end
  def tags
    query = params[:q]
    if query[-1,1] == " "
       query = query.gsub(" ", "")
       Tag.find_or_create_by_name(query)
    end
    @tags = ActsAsTaggableOn::Tag.all
    @tags = @tags.select { |v| v.name =~ /#{query}/i }
       respond_to do |format|
          format.json { render :json => @tags.collect{|t| {:id => t.name, :name => t.name }}}
       end
    end   

    def find_user_product(product)
         id_user = product.user_id
         user = User.find(id_user)
         user.user_cp
    end    
    
end

app/helpers/products_helper.rb
module ProductsHelper
  
  def find_id
    a = Product.last
    b = a.id
    return b
  end
  
  
  def url_painting(product)
     a = product.first
     return a.image_url
  end
  
  def find_user (user)
     user = User.find_by_id(user)
     return user.username
  end
  
  def find_picture(user)
    user = User.find_by_id(user)
    return user.picture
  end
  
  def find_evaluation_id(evaluation)
     if current_user.evaluations.nil?
         a = evaluation.first
          b = a.source_id
          return b
     else
       
     end
  end
  
  def find_sizes(product)
     size = product.all
     sizes = []
     size.each do |x|
        sizes << x.name
     end
     sizes.join(' - ')
  end
  
  def total_price(price, envio)
     total = price + envio
     return number_to_currency(total)
  end
  
  def related_items(product)
     a = product.first
     return a.image_url
  end
end

app/views/products/_comprar.html.erb
<div class="modal-compra">
  <div class="modal-body">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
	<h1>Resumen de tu compra</h1>
	<hr>
	<div class="row">
		<div class="span2">
			<%= image_tag(@product.paintings.first.image_url(:thumb))%>
		</div>
		<div class="span2">
			<strong><%= @product.title%></strong>
			<div id="tipo_envio">
				
			</div>
		</div>
		<div id="product_price" class="span2">	
			<%= number_to_currency(@product.price) %>
			<div id="costo_envio">
				<span id="envio"></span>
			</div>
			<hr>
			<div id="total">
			</div>
		</div>
	</div>
	<hr>
	<div class="span3">
	
		<%= form_for @product, url: envio_df_product_path(@product), remote: true do |f| %>
			<strong>
				Que opción de envío deseas:
			</strong>
			<% if @product.envio_df.nil? %>
				<% else %>
					<div><td><%= radio_button_tag 'envio', @product.envio_df, :class => 'Envío dentro DF' %><span id="envio_df"> Envío dentro DF </span>- $<%= @product.envio_df %> </td></div>
			<% end %>
			<% if @product.envio_int.nil? %>
				<% else %>
					<div><td><%= radio_button_tag 'envio', @product.envio_int, :class => 'Envío al interior del país' %><span id="envio_interior"> Envío interior del país </span>- $<%= @product.envio_int %></td></div>
			<% end %>
			
			<%= f.text_field :shipping, :class => "span2", :style => "display: none" %>
			<br/>
			<div class="span1">
				<%= f.submit "Elegir", class: "btn" %>
			</div>
		<% end %>
	</div>
	<div style="display:none" id="pagos" class="span4">
			<div id="paypal_checkout" style="width:150px; float:left;">
				<%= link_to "Pagar con Paypal", paypal_checkout_path(:product_id => @product.id), :class => "btn btn-success" %>
				<div style="width:80px"><%= image_tag("paypal.png")%></div>
			</div>
			<div id="mercadopago_checkout" style="width:200px; float:left">
				<!--	<%= link_to "Pagar con MercadoPago", "#", :class => "btn btn-success" %> -->
				<p><%= link_to "Pagar con MercadoPago", mercadopago_checkout_path(product_id: @product.id), :class => "btn btn-success" %></p>
					<div style="width:130px"><%= image_tag("mercadopago.png")%></div>
			</div>
		</div>
  </div>
</div>

<script>


</script>

app/views/products/_form.html.erb
<%= form_for (@product), :validate => true do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div sytle="padding-top: 2%" id="product_form" class="span3">
  <div class="field">
	<%= f.label :title, "*nombre del producto" %>
	<%= f.text_field :title, placeholder: "" %>
  </div>
  <div class="field">
	<%= f.label :brand, "*marca" %>
    <%= f.text_field :brand, placeholder: "" %>
  </div>
  <div class="field">
	<%= f.label :price, "*precio" %>
    <%= f.text_field :price, placeholder: " 0.00", :class => "span2", :style => "float:left" %><p>   MXN </p>
  </div>
  <br/>
  <div class="field">
	<%= f.label :description, "*describe tu producto" %>
    <%= f.text_area :description, rows: "4", placeholder: "" %>
  </div>
  <div class="field">
	<%= f.label :color, "*color" %>
    <%= f.text_field :color, placeholder: "" %>
  </div>
  <div class="field">
	<%= f.label :material, "*material" %>
    <%= f.text_field :material, placeholder: "" %>
  </div>
 
  <div class="field" style="height: 127px">
	<p style="float:left">
		<%= f.label :refund_policy, "*establece tus políticas de devolución" %>
	</p>
	<i style="margin-left: 5%; margin-top: -10%" id="policy_info" class="icon-info-sign icon-black"></i>
	<div class="popover fade top in" id="pop_policy" style="display:none; position: relative; top: -165px; left:-103px">
		<div class="arrow">
		</div>
		<div class="popover-inner">
			<div class="popover-content">
				<p>Ejemplo: "No aplica.", "Solo si el producto esta dañado.", "Solo si después de 30 días no ha sido entregado"</p>
			</div>
		</div>
	</div>
  </div>
	<p style="margin-top:-90px">	
	<%= f.text_area :refund_policy, rows: "3" %>
	</p>
 <div class="field">
    <%= f.label :size_tokens, "*información de tallas/medidas" %>
    <%= f.text_field :size_tokens, data: {load: @product.sizes}%>
  </div>
  <br/>
  <div class="field">
	<%= f.label :quantity, "*cantidad" %>
    <%= f.number_field :quantity, :placeholder => "", :in => 1..5 %>
  </div>
   
  <div class="field" style="height:20px">
		<p style="float:left">
			<%= f.label :tag_list, "*agrega tus tags" %>
		</p>		
			<i style="margin-left: 5%" id="tag_info" class="icon-info-sign icon-black"></i>
			<div class="popover fade top in" id="pop_tag" style="display:none; position: relative; top:-120px; left: -15px;">
				<div class="arrow">
				</div>
				<div class="popover-inner">
					<div class="popover-content">
						<p>¿Qué palabras describen a tu producto?(separalas por comas)</p>
					</div>
				</div>
			</div>
	  </div>
	
		<p>
		    <%= f.text_field :tag_list, placeholder: "*agrega tus tags", "data-pre" => @product.tags.map(&:attributes).to_json %>
		</p>
		
		<div>
			<%= link_to "opciones de envío", envio_path(:product_id => @product.id), {:id => "modal", :rel => "tab", :remote => true, 'data-controls-modal' =>  "modal-window", 'data-backdrop' => true, 'data-keyboard' => true, :class => 'btn'} %>
		</div>
		<br/>
		<div style="display:none" id="campo_enviodf">
			<p>
				<div style="float:left">Envío dentro DF $</div>
			    
			</p>
		</div>
		<div style="display:none" id="campo_envioint">
			<p>
				<div style="float:left">Envío interior del país $</div>
			</p>
		</div>
		<div style="display:none" id="campo_cp">
			<p>
				<div style="float:left">Recoger en CP: </div>
			</p>
		</div>
		<div style="display:none;" id="campo_estafeta">
			<div>Envío por Estafeta</div>
			<div id="estafeta_tipo" class="forma_estafeta"></div>
			<div id="estafeta_peso" class="forma_estafeta"></div>
			<div id="estafeta_alto" class="forma_estafeta"></div>
			<div id="estafeta_largo" class="forma_estafeta"></div>
			<div id="estafeta_ancho" class="forma_estafeta"></div>
			
			<%= f.text_field :envio_df, :class => "span2", :style => "display:none" %>
			<%= f.text_field :envio_int, :class => "span2", :style => "display:none" %>
			<%= f.text_field :cp, :class => "span2", :style => "display:none" %>
			<%= f.text_field :tipo_envio, :class => "span2", :style => "display:none" %>
			<%= f.text_field :peso, :class => "span2", :style => "display:none" %>
			<%= f.text_field :alto, :class => "span2", :style => "display:none" %>
			<%= f.text_field :largo, :class => "span2", :style => "display:none" %>
			<%= f.text_field :ancho, :class => "span2", :style => "display:none" %>
			
		</div>
		<hr>
		
</div>

<div style="margin-top: -20px" class="span6" id="mainImage">
	<div class="defaultMainImage">
	</div>
	<div id="ajax-status" style="float:left; display:none; margin-left:50%; margin-top:-100%; z-index: 3000"><%= image_tag("ajax-loader.gif") %></div>
	<div style="" class="well">
		<div class="span6">
			<div class="actions">
				<%= link_to 'Cancelar', products_path, class: "button-unfollow" %>
				<%= f.submit "Crear Producto", class: "button-want" %>
			</div>
		</div>
	</div>		
</div>
<% end %>

<div class="span3">
	<div class="field" id="file_image">
		<%= form_for(Painting.new, :remote => true) do |f| %>
		  <%= f.label :image, "*agrega tus fotos(máximo 4 fotos):", :class => "label_fotos" %>
		  <%= f.label :image, "La primera imagen, es la principal del producto", :class => "label_fotos" %>
		  <%= f.hidden_field :product_id, :value => @product.id %>
		  <%= f.file_field :image, multiple: true, name: "painting[image]"%>
		<% end %>
	</div>
	<ul id="productImagesSortable">
		<li id="image_small">
		</li>
	</ul>
</div>


<script id="template-upload" type="text/x-tmpl">
<div id="name" style="display:none">

	<div class="upload">
		<div class="span2">
			{%=o.name%}
	  		<div class="progress"><div class="bar" style="width: 0%"></div></div>
		</div
	</div>
</div>

</script>

<script type="text/javascript">
$("#product_form").keypress(function (evt) {
//Deterime where our character code is coming from within the event
	var charCode = evt.charCode || evt.keyCode;
	if (charCode  == 13) { //Enter key's keycode
	return false;
	}
});
</script>

app/views/products/_test.html.erb
<div class="modal-soxialit">
		<div style="min-height:50px; margin-bottom:0px; background-color:white; padding: 10px" class="well">
		<!--	<p style="float:right"><%= link_to "Follow", "#", :class => "btn btn-success"%></p> -->
			<p class="user_picture"><%= link_to image_tag(find_picture(@product.user_id)), user_path(@product.user_id) %> </p>
			<div class="product_credits"><%= "#{@product.title} by "%><%= link_to @product.brand, user_path(@product.user_id) %> </div>
			<div class="product_description"><%= @product.description %></div>
			<div class="product_description">Posted <%= distance_of_time_in_words(Time.now, @product.created_at) %> later</div>
			
			
		</div>
  <div style="background-color: #F2F0F0" class="modal-body center">
	<div class="row">
     	<div class="span8 offset1">	
				<% if @product.paintings.count >= 1 %>
				  <div class="product_modal">
					<%= link_to image_tag(url_painting(@product.paintings)), @product %>
				  </div>
				<% end %>
		</div>
	
	</div>
   </div>
  	<div class="modal-footer">
		<div class="product_tags">
			Tags: <%= raw @product.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
		</div>
	
 		<a href="#" class="btn">Close</a>
	</div>
</div>

app/views/products/edit.html.erb
<div class="row">
	<%= render 'form_edit' %>
</div>

app/views/products/index.js.erb
$('#contenedor').append("<%= escape_javascript(render :partial => @products) %>")

app/views/products/show.html.erb
<div class="row-fluid" style="background-color:white; margin-top:-7%; margin-left:-10%; width: 1150px">
	<div style="margin-left:3%; margin-right: 2%; margin-top:5%; margin-bottom: 5%; width:600px" class="span6">
	  <% unless @product.paintings.first.nil? %>
			<div class="mainpicture" style="float:left" id="painting_<%= @product.paintings.first.id %>">
			<%= image_tag(@product.paintings.first.image_url(:timeline))  %>
	  <% end %>
			</div>
				<ul id="productImagesSortable" style="float:right;">
						<% @product.paintings.each_with_index do |painting, index| %>
							<% if index < 4 %>
								<%= content_tag "div", class:"paintings", data: {id: painting.id } do %>
						 			<li id="smallImage" class="painting_<%= painting.id%>">
										<%= image_tag(painting.image_url(:thumb))%>
									</li>
								<% end %>
							<% end %>
						<% end %>
				</ul>
	</div>
	
<div style="margin-top:5%" class="span5">
	<div class="well" id="theme-shadow" style="background-color:white">
		<div class="description-medium">
			<div class="product_reputation">
			<% if signed_in? %>
				<span id="want_product_<%= @product.id %>">
					<i class="icon-star-empty icon-black"></i><%= pluralize @product.reputation_value_for(:votes).to_i, "Want" %>
					<br/>
					<br/>
				</span>
				
				<% if @product.user_id == find_evaluation_id(current_user.evaluations)%>
				<% elsif current_user && !current_user.voted_for?(@product) %>
					<span id="want_show_<%= @product.id %>">
				 		<%= link_to '<i class="icon-star-empty icon-white"></i> Want'.html_safe, vote_product_path(@product, type: "up"), :remote => true,  method: "post", :class => "button-want", id: "link" %>
					</span>
				<% end %>
			<% end %>
			</div>
		</div>
		<div class="description-main">
		  <%= @product.title %>
		<span class="description-low">by  </span> </div>
		<div class="description-strong"> 
		  <%= link_to @product.brand, user_path(@product.user_id) %>
		</div> 
		<hr>
		<div class="description-main">
		<!--	<div class="product_reputation">
			<% if signed_in? %>
				<span id="want_product_<%= @product.id %>">
					<i class="icon-star-empty icon-white"></i><%= pluralize @product.reputation_value_for(:votes).to_i, "Want" %>
				</span>
				<br/>
				<br/>
				<% if @product.user_id == find_evaluation_id(current_user.evaluations)%>
				<% elsif current_user && !current_user.voted_for?(@product) %>
					<span id="want_show_<%= @product.id %>">
				 		<%= link_to '<i class="icon-star-empty icon-white"></i> Want'.html_safe, vote_product_path(@product, type: "up"), :remote => true,  method: "post", :class => "button-want", id: "link" %>
					</span>
				<% end %>
			<% end %>
			</div> -->
			
			<%= number_to_currency(@product.price) %>
			<div style="margin-left:25%; margin-top:-5%">
				<%= link_to "Comprar", comprar_path(:product_id => @product.id), {:id => "modal", :rel => "tab", :remote => true, 'data-controls-modal' =>  "modal-window", 'data-backdrop' => true, 'data-keyboard' => true, :class => 'btn btn-success'} %>
			</div>
			<div class="description-low"> Cantidad disponible</div>
			<div class="description-medium"> <%= @product.quantity %> </div>
			<br/>
			<div class="description-low"> Medidas</div>
			<div style="float:left" class="description-medium"> <%= find_sizes(@product.sizes) %> </div>
			<span style="margin-left:5%"><%= link_to "Guía de medidas", tallas_path(:product_id => @product.id), {:id => "modal", :rel => "tab", :remote => true, 'data-controls-modal' =>  "modal-window", 'data-backdrop' => true, 'data-keyboard' => true, :class => 'btn'} %></span>
			<br/>
			<div class="description-low"> Tags: </div>
			<div class="description-tags"><%= raw @product.tag_list.map { |t| link_to t, tag_path(t) }.join(' - ') %></div>
			<br/>	
		</div>
		<hr>
		<div class="description-low"> Descripción del producto</div>
		<div class="description-medium"> <%= @product.description %> </div>
		<hr>
		<div class="description-low"> Colores</div>
		<div class="description-medium"> <%= @product.color %> </div>
		<hr>
		<div class="description-low"> Material</div>
		<div class="description-medium"> <%= @product.material %> </div>
		<hr>
		<div class="description-low"> Política de devoluciones</div>
		<div class="description-medium"> <%= @product.refund_policy %> </div>
		<hr>
		<div class="description-low"> Opciones de envío</div>
			<% if @product.envio_df.nil? %>
				<% else %>
				<div class="description-medium">Envío en DF:  <%= number_to_currency(@product.envio_df) %> </div>
			<% end %>
			<% if @product.envio_int.nil? %>
				<% else %>
				<div class="description-medium">Envío interior del país:  <%= number_to_currency(@product.envio_int) %> </div>
			<% end %>
			<% if @product.cp.nil? %>
			<% else %>
				<% if @product.cp.length > 0 %>
					<div class="description-medium">Recógelo en CP: <%= @product.cp %> (gratis)</div>
				<% end %>
			<% end %>
	</div>
	<div id="theme-shadow" style="background-color:white; height: auto" class="well">
		<div style="margin-left:0px" class="row">
			<div class="description-medium">
				Productos de <%= link_to @product.brand, user_path(@product.user_id) %>
			</div>
			
			<% @products.each do |product| %>
				<div style="padding:1%; width: 22.5%" class="span3">
					<% if product.title.nil? %>
					<% else %>
						<span class="description-low"><%= (product.title) %> </span>
						<div style="height: auto; margin-top: 10%"><%= link_to image_tag(url_painting(product.paintings)), product %></div>
						
					<% end %>
				</div>
			<% end %>
		</div>
	</div>
</div>
</div>