config/routes.rb
DeviseFacebook::Application.routes.draw do

  resources :feedbacks

  resources :sizes

  resources :paintings

  root :to => 'static_pages#home'

  root :to => 'static_pages#home'
  get "products/tags" => "products#tags", :as => :products_tags

  
  devise_for :users

  resources :products 
  
  resources :users

  resources :user_steps

  resources :products do
     member { post :vote }
     put :envio_df, on: :member
  end
  
  match '/tags', to: 'tags#show_tags'
  match '/auth/:provider/callback', to: 'authentications#create', as: 'signin'
  
  get 'tags/:tag', to: 'products#index', as: :tag
  
  get 'paypal/checkout', to: 'products#paypal_checkout'
  
  get '/comprar', to: 'products#comprar'
  
  get '/envio', to: 'products#envio'
  
  get '/tallas', to: 'products#tallas'
    
  get 'mercadopago/checkout', to: 'products#mercadopago_checkout'
  
  get "terms", to:'static_pages#terms'

  get "privacy", to:'static_pages#privacy'

  get "faq", to:'static_pages#faq'

  get "static_pages/start"

  get "static_pages/buy"

  get "static_pages/sell"

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="span4">
    <p style="float:left; font-size:0.8em">&#169; Soxialit</p>
	<p style="font-size:0.8em; margin-left: 40%">   Contacto: info@soxialit.com </p>
  </div>
 
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<%= link_to "Soxialit Alpha", root_path, id: "logo" %>
				<nav>
					<ul class="nav pull-right">
              			<% if user_signed_in? %>
				           <!--<li style="color:green; margin-top:10px">Signed in as <%= current_user.email %>. 
				            	Not you? 
				            </li> -->
							<li><%= link_to "Escribe aquí tus comentarios", feedbacks_path %></li>
							<li><%= link_to "Productos Random", products_path, :style => "color: #00B174;" %></li>
							<li> <%= link_to "Crea un producto", new_product_path, style:"color: #ff5a54" %>
							<li> <%= link_to "Sign out", destroy_user_session_path, method: "delete" %></li>
				           <!-- <li id="fat-menu" class="dropdown"> 
				              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
				                Account <b class="caret"></b>
				              </a>
				              <ul class="dropdown-menu">
				                <li><%= link_to "Profile", '' %></li>
				                <li><%= link_to "Settings", edit_user_registration_path %></li>
				                <li class="divider"></li>
				                <li>
				                  <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
				                </li>
							  </ul>
				            </li> -->
				         <% else %>
				         <!--   <%= link_to "Sign up", new_user_registration_path %> or
						    <%= link_to "Sign in", new_user_session_path %>
						    <%= link_to 'Login with Facebook', '/auth/facebook/' %>  -->
				         <% end %>
              		</ul>
              	</nav>
			</div>
		</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Soxialit</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container"> 
   <% flash.each do |type, message| %>
      <div class="alert <%= flash_class type %>">
        <button class="close" data-dismiss="alert">x</button>
        <%= message %>
      </div>
    <% end %>
    <%= yield %>
	<div id="modal-id"></div>
	<div id="loading_image" style="display:none; margin-left:50%"><%= image_tag("ajax-loader.gif") %></div>
    <%= debug(params) if Rails.env.development? %>
  </div>
<div class="container">
	<div class="span12">
		<%= render 'layouts/footer' %>
	</div>
  </div>

</body>
</html>